### PR TITLE
Update dotnet.md

### PR DESCRIPTION
**Pull request by michieal**
Fixed a small error that hoses the process. Also, added in comments on the process.

### CODE REVIEW

**Comment by michieal** [comment]
Should I also add this in, in a "if all else fails" case scenario?

    Create a nuget.config file in the root of your project or solution (if it doesn't already exist).

    Open or create the nuget.config file, and add the following:

   ```xml

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <packageSources>
        <add key="LuaAPINugetSource" value="/path/to/editor/linux-editor-mono/nuget_packages" />
        <!-- Add other package sources if needed -->
      </packageSources>
    </configuration>
```
    Replace /path/to/editor/linux-editor-mono/nuget_packages with the correct path to your local NuGet source.

    Save the nuget.config file.

With this configuration, you don't need to manually specify the package source in your project file. The NuGet restore process will automatically consider the sources listed in the nuget.config.

**Comment by Trey2k** [comment]
> Should I also add this in, in a "if all else fails" case scenario?

If it is useful info, I do not see why not

**Comment by michieal** [comment]
Okay. Done.

**Comment by Trey2k** [comment]
Thanks!

**Pull request merged**
